### ISSUE TITLE
Time should not show seconds

### ISSUE THREAD

**Issue by RatikKapoor** [relectric-car-team/user-interface#31]
Showing the seconds on the Home Screen might be distracting to drivers. I would still recommend keeping the setInterval to run every 1000ms so that the minute value is updated on time.

![image](https://user-images.githubusercontent.com/14501811/109595821-733c8900-7ad2-11eb-8006-d6e47e366c5f.png)

**Comment by brooke-k** [comment]
Pull request has been put in. The only code that has changed is that for formatting the display values. Still updating every second.
